name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile d2xl-cIOS
      uses: ./.github/actions
      id: asdf
    - uses: actions/upload-artifact@v1
      with: 
        name: d2xl-cios
        path: build/

